# Use the official Node.js image as a parent image
FROM node:lts

# # Set the working directory
# WORKDIR /workspace

# # Install dependencies
# COPY package*.json ./
# RUN npm install

# # Copy the rest of the application code
# COPY . .

# # Expose the port Next.js runs on
# EXPOSE 3000

# # Start the Next.js application
# CMD ["npm", "run", "dev"]
